# Generated by Django 4.1 on 2022-09-01 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(default=1234567890, max_length=10),
            preserve_default=False,
        ),
    ]
