# Generated by Django 4.1 on 2022-08-16 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_payment_is_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
