# Generated by Django 4.1 on 2022-08-16 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_alter_payment_is_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='is_paid',
        ),
    ]
