# Generated by Django 4.1.1 on 2022-10-11 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_product_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('', 'Select'), ('waiting', 'waiting'), ('delivering', 'delivering'), ('received', 'received')], default='waiting', max_length=100),
        ),
    ]
