# Generated by Django 4.1 on 2022-08-19 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0008_alter_order_customer_alter_ordereditem_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='ordereditem',
            name='price',
        ),
    ]
