# Generated by Django 4.1 on 2022-08-19 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_remove_order_total_amount_remove_ordereditem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordereditem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=10),
            preserve_default=False,
        ),
    ]
