# Generated by Django 4.1 on 2022-08-19 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0011_alter_ordereditem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
