# Generated by Django 4.1 on 2022-08-20 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0012_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadanimalimages',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animal_uploaded_image', to='ecommerce.animal'),
        ),
    ]
