# Generated by Django 4.1 on 2022-08-24 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0014_order_delivery_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='animal_classes',
            field=models.CharField(choices=[('', 'Classes of animals'), ('Poultry', 'Poultry'), ('Cattle', 'Cattle'), ('Sheep', 'Sheep')], default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_order', to='ecommerce.order'),
        ),
    ]
