# Generated by Django 4.1 on 2022-08-24 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0015_category_animal_classes_alter_payment_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='animal_category', to='ecommerce.category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='animal_classes',
            field=models.CharField(choices=[('', 'Classes of animals'), ('Poultry', 'Poultry'), ('Cattle', 'Cattle'), ('Sheep', 'Sheep'), ('Goat', 'Goat'), ('Swine', 'Swine')], max_length=100),
        ),
    ]
