# Generated by Django 4.1 on 2022-08-24 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0017_alter_animal_category_alter_ordereditem_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='animal_classes',
        ),
    ]
