# Generated by Django 4.1 on 2022-08-25 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0019_animal_image_slug_1_animal_image_slug_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='discount',
            field=models.BigIntegerField(default=0, null=True),
        ),
    ]
