# Generated by Django 4.1 on 2022-08-31 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0022_payment_name_payment_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='is_popular',
            field=models.CharField(choices=[('Yes', True), ('No', False)], default=False, max_length=10),
        ),
    ]
