# Generated by Django 4.1 on 2022-08-31 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0023_animal_is_popular'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='discount',
        ),
    ]
