# Generated by Django 4.1 on 2022-08-31 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0024_remove_animal_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='is_popular',
            field=models.CharField(choices=[('No', False), ('Yes', True)], default=False, max_length=10),
        ),
    ]
